pipeline {
    agent any

    stages {
        stage("Execute Unit Tests") {
            parallel {
                stage('Unit Tests - Backend') {
                    agent {
                        docker {
                            image 'snakee/golang-junit:1.21'
                            reuseNode true
                            args '-e GOCACHE=/tmp/go-cache -e GOPATH=/tmp/go-path'
                        }
                    }

                    steps {
                        dir('bugtracker-backend') {
                            sh 'go test -v ./...'
                        }
                    }
                }

                stage('Unit Tests - Frontend') {
                    agent {
                        docker {
                            image 'node:20-alpine'
                            reuseNode true
                        }
                    }

                    steps {
                        dir('bugtracker-frontend') {
                            sh '''
                              npm ci
                              npm test
                              mkdir -p reports
                              mv coverage reports/
                            '''
                        }
                    }

                    post {
                        always {
                            junit 'bugtracker-frontend/test-results.xml'
                            publishHTML(target: [
                                reportName: 'Frontend Test Coverage',
                                reportDir: 'bugtracker-frontend/reports/coverage',
                                reportFiles: 'index.html'
                            ])
                        }
                    }
                }
            }
        }

        stage('Launch Application') {
            agent {
                docker {
                    image 'docker:27.5.1'
                    reuseNode true
                    args '-v /var/run/docker.sock:/var/run/docker.sock -u 0'
                }
            }
            steps {
                sh '''
                  docker compose up --build -d
                '''
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
